### PR TITLE
Add PRIDE validation package

### LINKED ISSUE #2: [Feature] Add validation/QC-package for PRIDE
PRIDE is a relatively easy target for validation since it requires basic information from Investigation file but also some more sophisticated metadata from Study and Assay files' ISA processes. This is also a nice way to expand the ARCExpect library of V2 when needed.

### PR DESCRIPTION
**Pull request by omaus**
This PR
- adds PRIDE validation package
- closes #2

### CODE REVIEW

**Review by kMutagene — CHANGES_REQUESTED** [review]
@omaus 

Nice progress so far. I think my review comments on https://github.com/nfdi4plants/arc-validate/pull/88 should be addressed before publishing (meanining: setting `Publish true` in the header). 

Small request: could you add more metadata to the header? I know [these](https://github.com/nfdi4plants/arc-validate-package-registry?tab=readme-ov-file#optional-fields) are optional but especially tags would be nice. After that we can merge this so that it is accessible for the github api-based package installation already, and move to [production](https://avpr.nfdi4plants.org/) once the helpers are refactored.

**Comment by kMutagene** [comment]
@omaus note that publishing and merging into this repo are two separate [things](https://github.com/nfdi4plants/arc-validate-package-registry?tab=readme-ov-file#package-publication-workflow). 

We can absolutely merge this when more metadata is added.

**Comment by kMutagene** [comment]
@omaus sorry to nudge you so much but can you please add author and tag metadata so we can merge this? Should not take long.

**Comment by omaus** [comment]
> @omaus sorry to nudge you so much but can you please add author and tag metadata so we can merge this? Should not take long.

Yeah thx, pls check if it is done right (I'm esp. unsure about the `publish: true`). 👍🏻

**Comment by kMutagene** [comment]
Lgtm, but pls do not set `publish` - this is intended for full immutabke release, and iirc we want to adapt arcexpect api before that

**Comment by kMutagene** [comment]
Lgtm, but pls do not set `publish` - this is intended for full immutabke release, and iirc we want to adapt arcexpect api before that

**Comment by kMutagene** [comment]
But commiting to this repa makes the package available as prerease already

**Comment by omaus** [comment]
> Lgtm, but pls do not set `publish` - this is intended for full immutable release, and iirc we want to adapt arcexpect api before that

Done.

**Comment by kMutagene** [comment]
thanks @omaus, heads up taht i will push some changes to your branch to test some ci capabilities

**Review by kMutagene — CHANGES_REQUESTED** [review]
allright, testing pipeline seems to work and also caught multiple problems (see pipeline output). 

Please make sure that the version in the yaml metadata is the same as indicated in the file name, and make sure that the script can run. Compilation of the script in ci fails, and i suspect that that is due to the versions of the nuget packages not being pinned, and ARCExpect API having changed since you submitted the PR.

I will add a test that checks that all nuget references are pinned.

**Comment by omaus** [comment]
@kMutagene 

Unit test says that version is wrong. I don't see why that should be the case. The file's name is "pride@1.0.0.fsx", YAML tags:

```yaml
MajorVersion: 1
MinorVersion: 0
PatchVersion: 0
```

???

**Comment by kMutagene** [comment]
> ???

Those are the default values the metadata class gets initialized with if the frontmatter is invalid **!!!**
Note that also the `StagingDirectory.FileContent.All files have valid metadata` test fails. The issue is that your file gets checked out with LF on windows instead of CRLF. Not sure why but i really do not care, ill just replace line endings on parsing frontmatter.

**Comment by kMutagene** [comment]
Also, `name` in ontology tags should be `Name`, which is my bad.

**Review by kMutagene — APPROVED** [review]

**Pull request merged**
